---
title: ''
output:
  html_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# load libraries
library(tidyverse)
library(gt)
```


```{r stains, message=FALSE}
# import raw data
stain_raw <- read_csv("../data/her2_cases.csv")

# Assign DISH group
stain_dish <- 
  stain_raw %>% 
  mutate(
    dish_grp = case_when(
      `Her2 Chr17 ratio2` >= 2.0 & `Her2 signal` >= 4.0 ~ 1,
      `Her2 Chr17 ratio2` >= 2.0 & `Her2 signal` < 4.0 ~ 2,
      `Her2 Chr17 ratio2` < 2.0 & `Her2 signal` >= 6.0 ~ 3,
      `Her2 Chr17 ratio2` < 2.0 & `Her2 signal` >= 4.0 & 
        `Her2 signal` < 6.0 ~ 4,
      `Her2 Chr17 ratio2` < 2.0 & `Her2 signal` < 4.0 ~ 5,
      TRUE ~ as.numeric(NA)
    ),
    dish_grp_z = case_when(
      `z_Her2 Chr17 ratio` >= 2.0 & `z_Her2 signal` >= 4.0 ~ 1,
      `z_Her2 Chr17 ratio` >= 2.0 & `z_Her2 signal` < 4.0 ~ 2,
      `z_Her2 Chr17 ratio` < 2.0 & `z_Her2 signal` >= 6.0 ~ 3,
      `z_Her2 Chr17 ratio` < 2.0 & `z_Her2 signal` >= 4.0 & 
        `Her2 signal` < 6.0 ~ 4,
      `z_Her2 Chr17 ratio` < 2.0 & `Her2 signal` < 4.0 ~ 5,
      TRUE ~ as.numeric(NA)
    ),
    Type = case_when(
      Type == "Breast" ~ "Breast Cases",
      Type == "GI" ~ "GI Cases"
    )
  )

stain_dish %>% 
  select(
    Type,
    Pathologist,
    Cytotech,
    `Case ID`,
    `IHC Concurrent`,
    `HER2/CEP17 current` = `Her2 Chr17 ratio2`,
    `HER2/CEP17 new` = `z_Her2 Chr17 ratio`,
    `CEP17 signal current` = `Chromosome 17 signal`,
    `CEP17 signal new` = `z_Chromosome 17 signal`,
    `HER2 signal current` = `Her2 signal`,
    `HER2 signal new` = `z_Her2 signal`,
    `DISH Group current` = dish_grp,
    `DISH Group new` = dish_grp_z,
    `comments (current)` = Her2_comments,
    `comments (new)` = z_Her2_comments
  ) %>% 
  gt(groupname_col = "Type", 
     rowname_col = "Pathologist") %>% 
  tab_header(title = 
               md("**Table 1: Pairwise results of current and new Her2Dual ISH Test**")
  ) %>% 
  fmt_missing(
    columns = everything(),
    missing_text = "--"
  ) %>% 
  cols_align(
    align = "center",
    columns = c(3, 5:13)
  ) %>% 
 tab_style(
    style = 
      cell_fill(color = "yellow"),
      locations = cells_body(
      rows = `DISH Group current` != `DISH Group new`)
  ) %>%
  tab_options(
    column_labels.font.weight = "bold",
    table.font.size = 12,
    table.width = pct(100)
  )
```

